---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age157u97hxaahvdkj5hswlwdys35ycu7xvqn44pcy5zfd4j56xpxv3q7sgsat
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age157u97hxaahvdkj5hswlwdys35ycu7xvqn44pcy5zfd4j56xpxv3q7sgsat
