# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HaO5X+4+DNcT3SgnhYoiVBRfP0fOYGes,iv:QFxmByOl9JRN3eSgo1E0e3TbYKB1MGtqA77yf+XTfNc=,tag:lspEjLHx0Zxr7VQxb114Eg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:XyVLr3WKpcf1Jdv5PA3UHLJwJNiZWtq7Xqfc3CZAZH49l6SPCg==,iv:e7LM3IpfdJCT+8YvymGQmcbvTOFF3znLCWMOtJUfu7E=,tag:Iiv4oGKiLwyUX86erVBjOw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JwHiD44OOGmkM///sTXymXMmjmpB,iv:mekly9vmFwpbMf94lKnBBWvJvaReXv2wlBglRc4DBlY=,tag:cU0NzTTQRSHarNcpEB5h7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age157u97hxaahvdkj5hswlwdys35ycu7xvqn44pcy5zfd4j56xpxv3q7sgsat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbTFrM3NsMEdZeVg3WjQ1
            RmpYMWRtcWFBcEtxZFVYWlFtT0o1ZXdPK3d3CndZVG1CY2c2WnVGNDNHRTgzSEx6
            WURYY1JGVzZoeU1FZ0dRa20vMUMyeUkKLS0tIHlaaHRrOEZSaWNGclZodEFzdnhu
            T3ZUWS9VaGJLczZwZDYvT2xNZ1hNbXMKtN3ChuynQcbsIt3Xe9SI66kzRtC3gxIb
            woHULmF+T5lj7QTot3066vMscbtVuLc0HUeDmZXJxdbBEVflu40FwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-14T00:25:52Z"
    mac: ENC[AES256_GCM,data:rYEmSAbavB21nVrJVdbpO7Yq8HpfaBVFO0vpLNDw4AsZ7kUoOP5XDFIJCODoHNeAj42izUUU1qTUEXsRC6CqImQgWA9ExPVRUoANpqfqitvfM5Nca8sXI9Est3+Mpuo+Bi1bTjdcdAoezbgFuta9xjCWi5FqF2cWE5CQ0J5zEF0=,iv:lOPG9EqccJQidjFm4hMhdftp/Jh7pMGvdChmjCch2ek=,tag:YRvmTFrJfnwgXpw3GNc58w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
